/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        primary: '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        secondary: '#bec8d2',
        'on-secondary': '#28313a',
        'secondary-container': '#3e4851',
        'on-secondary-container': '#acb6c1',
        'secondary-fixed': '#dae4ef',
        'secondary-fixed-dim': '#bec8d2',
        tertiary: '#ffffff',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#e2e2e2',
        background: '#141d26',
        'on-background': '#dde3ec',
        'on-surface': '#dde3ec',
        'on-surface-variant': '#c4c7c8',
        outline: '#8e9192',
        'outline-variant': '#444748',
        'accent-glow': 'rgba(255, 255, 255, 0.05)',
        'glass-fill': 'rgba(20, 29, 38, 0.7)',
        'border-subtle': 'rgba(255, 255, 255, 0.12)',
        'surface-base': '#0A1016',
        'surface-elevated': '#141D26',
        'surface-container': '#1a2027',
        'surface-container-low': '#161c22',
        'surface-container-high': '#252b31',
        'surface-container-highest': '#2f353c',
        'surface-container-lowest': '#090f15',
        'surface-bright': '#343a41',
        'surface-variant': '#2f353c',
        'surface-dim': '#0e141a',
        'surface-tint': '#c6c6c7',
        // Backward-compatible aliases mapped to dark LedgerIQ surfaces
        surface: {
          DEFAULT: '#141d26',
          primary: '#141D26',
          secondary: '#1a2027',
          tertiary: '#252b31',
          border: 'rgba(255, 255, 255, 0.12)',
          base: '#0A1016',
          elevated: '#141D26',
        },
        accent: {
          green: '#dae4ef',
          'green-hover': '#bec8d2',
          blue: '#bec8d2',
          'blue-hover': '#acb6c1',
        },
        text: {
          secondary: '#c4c7c8',
          muted: '#8e9192',
        },
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-fraunces)', 'Georgia', 'serif'],
        'display-lg': ['var(--font-fraunces)', 'Georgia', 'serif'],
        'headline-lg': ['var(--font-fraunces)', 'Georgia', 'serif'],
        'headline-md': ['var(--font-fraunces)', 'Georgia', 'serif'],
        'headline-lg-mobile': ['var(--font-fraunces)', 'Georgia', 'serif'],
        'body-sm': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'data-mono': ['var(--font-inter)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '300' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      animation: {
        'spin-slow': 'spin 2s linear infinite',
      },
      boxShadow: {
        glass: '0 4px 24px rgba(0,0,0,0.2)',
        glow: '0 0 20px rgba(255,255,255,0.05)',
      },
    },
  },
  plugins: [],
}
