"""
LedgerIQ Local ERP Agent
========================
Runs on the client's local network. Reads ERP data (Excel / SAP / Logo / Mikro)
on a configurable schedule and syncs standardized ledger records to the LedgerIQ
API so the Gemini reconciliation agent always operates on fresh data.

Usage:
    python main.py
"""
import os
import sys
import json
import asyncio
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)

def load_enterprise_config():
    """Reads config.json generated by LedgerIQ and injects it into environment variables."""
    config_path = "config.json"
    
    if not os.path.exists(config_path):
        logging.error("CRITICAL: config.json not found in the current directory.")
        logging.error("Please download the agent package from the LedgerIQ dashboard and extract config.json here.")
        sys.exit(1)
        
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        cloud = config.get("ledgeriq_cloud") or config.get("lumina_cloud") or {}
        os.environ["ERP_SYNC_API_URL"] = os.environ.get("ERP_SYNC_API_URL") or cloud.get("server_url", "http://localhost:8000")
        os.environ["ERP_SYNC_API_KEY"] = os.environ.get("ERP_SYNC_API_KEY") or cloud.get("api_key", "")
        os.environ["ERP_POLL_INTERVAL_SECONDS"] = str(config.get("sync_settings", {}).get("poll_interval_seconds", 3600))
        os.environ["ERP_SOURCE_TYPE"] = config.get("erp_connection", {}).get("driver", "excel")
        os.environ["ERP_DATA_PATH"] = config.get("erp_connection", {}).get("local_file_path", "./data/erp_export.xlsx")
        os.environ["COMPANY_ID"] = config.get("agent_metadata", {}).get("company_id", "")
        
        integration_name = config.get("agent_metadata", {}).get("integration_name", "Unknown")
        logging.info(f"Enterprise configuration loaded successfully. Integration: {integration_name}")
        logging.info(f"Target LedgerIQ API: {os.environ['ERP_SYNC_API_URL']}")
        logging.info(f"Active ERP Driver: {os.environ['ERP_SOURCE_TYPE'].upper()}")
        
    except Exception as e:
        logging.error(f"CRITICAL: Failed to parse config.json. Verify file integrity. Details: {e}")
        sys.exit(1)

if __name__ == "__main__":
    load_enterprise_config()
    # Import AFTER config is loaded so environment variables are populated
    from scheduler.cron_runner import start_scheduler
    asyncio.run(start_scheduler())